-- Gaffer — Re-enable RLS (SUPERSEDED)
--
-- This script has been replaced by migrations/004_reenable_rls.sql, which
-- does the same 8 ALTER TABLE statements plus tightens the SECURITY DEFINER
-- helper function grants flagged by the security advisor. Run that file
-- instead — this one is kept only so old links/notes referencing it don't
-- 404; do not run both.
--
-- Rollback if it 42501s again: disable_rls.sql (repo root, next to this
-- file).
